name: Docker release image publisher

on:
  pull_request:
    branches:
      - release
  push:
    branches:
      - release

jobs:
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup opnenjdk-17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: samillmu/luffy

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            DB_URL=${{ secrets.DB_URL }} 
            DB_USERNAME=${{ secrets.DB_USERNAME }} 
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CIENT_ID }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          tags: | 
            samillmu/luffy:latest
            ${{ steps.meta.outputs.tags }}
