# .github/workflows/pr-labeler.yml

name: Reabase labeler

on:
  pull_request:
    branches:
      - 'main'

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

enable:
  issues: false
  prs: true

# 레이블
labels:
  '🚀 rebase merge':
    include:
      - '\b\b'
