name: Start api server

on:
  workflow_run:
    workflows:
      - "Docker image publisher"
    types:
      - completed
  pull_request:
    branches:
      - main

  start_server:
    name: start server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            docker pull samillmu/luffy:latest
            docker ps -aq | xargs docker stop | xargs docker rm
            docker run -p 8080:8080 samillmu/luffy:latest
